onlyBuiltDependencies:
  - '@swc/core'
  - '@parcel/watcher'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver

allowedDeprecatedVersions:
  node-domexception: '*'
  whatwg-encoding: '*'

peerDependencyRules:
  allowAny:
    - node-fetch

packages:
  - 'apps/**'
  - 'packages/**'